/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataTable: typeof import('primevue/datatable')['default']
    PkgCalendar: typeof import('./src/components/atoms/PkgCalendar.vue')['default']
    PkgInputIcon: typeof import('./src/components/atoms/PkgInputIcon.vue')['default']
    PkgSelect: typeof import('./src/components/atoms/PkgSelect.vue')['default']
    PkgTable: typeof import('./src/components/organisms/PkgTable.vue')['default']
    Select: typeof import('primevue/select')['default']
  }
}
